{{- if .Values.dependencies.secrets -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "nqlabs-service.fullname" . }}-deps
  labels:
    {{- include "nqlabs-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.storeKind | default "ClusterSecretStore" }}
    name: {{ .Values.externalSecrets.store | default "nqlabs-openbao" }}
  target:
    name: {{ include "nqlabs-service.fullname" . }}-deps
    creationPolicy: Owner
  data:
    {{- range .Values.dependencies.secrets }}
    - secretKey: {{ .envVar }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- with .remoteRef.property }}
        property: {{ . }}
        {{- end }}
    {{- end }}
{{- end }}
