{{- if .Values.limitRange.enabled -}}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "nqlabs-service.fullname" . }}
  labels:
    {{- include "nqlabs-service.labels" . | nindent 4 }}
spec:
  limits:
    {{- toYaml .Values.limitRange.limits | nindent 4 }}
{{- end }}
