{{- if .Values.resourceQuota.enabled -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "nqlabs-service.fullname" . }}
  labels:
    {{- include "nqlabs-service.labels" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.resourceQuota.hard | nindent 4 }}
  {{- with .Values.resourceQuota.scopes }}
  scopes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.resourceQuota.scopeSelector }}
  scopeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
