apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-data
  namespace: monitoring
  labels:
    app.kubernetes.io/name: gatus
    app.kubernetes.io/component: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
