apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-default-deny
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: https://github.com/NicolasQueiroga/nqlabs-platform.git
    targetRevision: HEAD
    path: platform/security
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
