---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: "1.24.4"
      helm:
        releaseName: tempo
        valueFiles:
          - $values/infrastructure/monitoring/tempo/values.yaml
    - repoURL: https://github.com/NicolasQueiroga/nqlabs-platform.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/NicolasQueiroga/nqlabs-platform.git
      targetRevision: HEAD
      path: infrastructure/monitoring/tempo
      directory:
        include: "routes.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyroscope
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: pyroscope
      targetRevision: "2.1.0"
      helm:
        releaseName: pyroscope
        valueFiles:
          - $values/infrastructure/monitoring/pyroscope/values.yaml
    - repoURL: https://github.com/NicolasQueiroga/nqlabs-platform.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/NicolasQueiroga/nqlabs-platform.git
      targetRevision: HEAD
      path: infrastructure/monitoring/pyroscope
      directory:
        include: "routes.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform
  source:
    repoURL: https://github.com/NicolasQueiroga/nqlabs-platform.git
    targetRevision: HEAD
    path: infrastructure/monitoring/otel-collector/management
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
