#!/usr/bin/env bash
# Generate BareMetalHost manifests from inventory.csv.
#
# Usage:
#   cd infrastructure/metal3/hosts
#   ./generate.sh
#
# This script reads inventory.csv and produces:
#   - proxmox-bmc-secret.yaml  (shared BMC Secret for all Proxmox VMs)
#   - <name>.yaml               (one BareMetalHost per row)
#
# The generated files are committed to git.  Re-run whenever inventory.csv
# changes.  Do NOT edit generated files directly — edit inventory.csv and
# re-run this script.
#
# For physical NUCs with unique BMC credentials, add a Secret manually in
# a separate file (e.g., nuc-01-bmc.yaml) and reference it via the
# bmc_credentials column.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
INVENTORY="${SCRIPT_DIR}/inventory.csv"
PROXMOX_BMC_SECRET="${SCRIPT_DIR}/proxmox-bmc-secret.yaml"

# Proxmox BMC credentials (shared across all Proxmox VMs)
# These are the proxmox-redfish daemon credentials (Proxmox root@pam)
PROXMOX_USER_B64="$(echo -n 'root@pam' | base64)"
PROXMOX_PASS_B64="$(echo -n 'queiroga' | base64)"

# --- Generate shared Proxmox BMC Secret ---
cat > "${PROXMOX_BMC_SECRET}" << EOF
# Shared BMC credentials for all Proxmox VMs.
# All VMs use the same proxmox-redfish daemon with the same Proxmox credentials.
# Generated by generate.sh — do not edit directly.
---
apiVersion: v1
kind: Secret
metadata:
  name: proxmox-bmc
  namespace: metal3
type: Opaque
data:
  username: ${PROXMOX_USER_B64}
  password: ${PROXMOX_PASS_B64}
EOF

echo "Generated: proxmox-bmc-secret.yaml"

# --- Generate BareMetalHost manifests ---
# Skip comment rows (starting with #) and empty lines.
# The header row (starting with "name,") is also skipped.
grep -v '^#' "${INVENTORY}" | grep -v '^$' | grep -v '^name,' | while IFS=, read -r \
    name vmid mac bmc_address cluster role provider accepted online cores memory bmc_credentials; do

    # Skip empty lines
    [ -z "$name" ] && continue

    # Determine BMC credentials secret name
    if [ "$bmc_credentials" = "proxmox-shared" ]; then
        bmc_secret="proxmox-bmc"
    else
        bmc_secret="$bmc_credentials"
    fi

    # Check if host has BMC (physical NUCs without BMC use "none")
    has_bmc=true
    if [ "$bmc_address" = "none" ] || [ -z "$bmc_address" ]; then
        has_bmc=false
    fi

    # Convert booleans to lowercase
    accepted_lower=$(echo "$accepted" | tr '[:upper:]' '[:lower:]')
    online_lower=$(echo "$online" | tr '[:upper:]' '[:lower:]')

    output_file="${SCRIPT_DIR}/${name}.yaml"

    # For unaccepted hosts (accepted=false), use externallyProvisioned
    # to prevent BMO from managing them. BMO v0.13.1 doesn't have an
    # "accepted" field — hosts are managed when they have BMC details
    # and online=true. externallyProvisioned=true tells BMO the host is
    # managed by an external process and should not be provisioned.
    if [ "$accepted_lower" = "false" ]; then
        external_prov="  externallyProvisioned: true"
    else
        external_prov=""
    fi

    # Build BMC section (skip for physical hosts without BMC)
    if [ "$has_bmc" = "true" ]; then
        bmc_section="  bmc:
    address: ${bmc_address}
    credentialsName: ${bmc_secret}
    disableCertificateVerification: true"
    else
        bmc_section=""
    fi

    cat > "${output_file}" << EOF
# BareMetalHost: ${name} (${provider})
#
# Generated from inventory.csv — do not edit directly.
# To change: edit inventory.csv and run ./generate.sh
#
# Cluster: ${cluster}
# Role: ${role}
# MAC: ${mac}
# BMC: ${bmc_address}
# Credentials: ${bmc_secret}

---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: ${name}
  namespace: metal3
  labels:
    cluster: ${cluster}
    role: ${role}
    provider: ${provider}
spec:
  online: ${online_lower}
  bootMACAddress: ${mac}
  bootMode: UEFI
  hardwareProfile: unknown
${bmc_section:+${bmc_section}
}${external_prov}
EOF

    echo "Generated: ${name}.yaml"
done

echo ""
echo "Done. Review changes with: git diff"
echo "Commit with: git add *.yaml && git commit -m 'update BareMetalHost inventory'"
